### ISSUE TITLE
Flake does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux' 

### ISSUE THREAD

**Issue by phaitonican** [fb87/nixos-orangepi-5x#3]
Getting this error:

error: flake 'git+file:///home/cenk/nixos-orangepi-5x' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'

Any idea? sorry im very noob

**Comment by ryan4yin** [comment]
This repository provides a `packages.aarch64-linux.default` instead of `packages.x86_64-linux.default`, which assumes that you are compiled natively: https://github.com/fb87/nixos-orangepi-5x/blob/v5.10.x/flake.nix#L398C7-L398C37

And cross-platform compilation needs to modify the content of flake.nix.
If you are not familiar with NixOS, I suggest you refer to this document:

Https://nixos-and-flakes.thiscute.world/development/cross-platform-compilation

**Comment by phaitonican** [comment]
Thanks very much I will try to figure this out thanks :)
